user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "p=978") { return 302 /best-vs-code-extensions-for-rust-development/; }
            if ($query_string = "p=727") { return 302 /introduction-to-rust/; }
            if ($query_string = "p=783") { return 302 /getting-started-with-rust/; }
            if ($query_string = "p=832") { return 302 /improve-developer-productivity/; }
            if ($query_string = "p=881") { return 302 /game-development-in-rust-strategy-game-1/; }
            if ($query_string = "p=936") { return 302 /game-development-in-rust-making-a-strategy-game-2/; }
            if ($query_string = "p=950") { return 302 /game-development-in-rust-making-a-strategy-game-3/; }
        }
    }
}
